version: "3"
services:
  my-app:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    command: npm start
    volumes:
      - ./my-app:/app

  cypress:
    image: cypress-image-jose3
    depends_on:
      - my-app
    volumes:
      - ./cypress:/e2e
    command: npm run cypress:run
